# Test image for ArgsEscaped behavior.
# cplatpublic.azurecr.io/argsescaped:latest
FROM mcr.microsoft.com/windows/nanoserver:1809@sha256:cfb490663097bfb37ccdde9fcc5a414f1c80f5ae1cb1de9011a25366ba719115
ENTRYPOINT cmd.exe /c
CMD ping -t 127.0.0.1
