# Test image for ArgsEscaped behavior.
# cplatpublic.azurecr.io/argsescaped:latest
FROM mcr.microsoft.com/windows/nanoserver:1809@sha256:244f1c6f590ca5a417c241a11cd6719a456f9771c45a0c2b195d5636763a7f0e
ENTRYPOINT cmd.exe /c
CMD ping -t 127.0.0.1
