trigger:
  - main

parameters:
  - name: rpmVersion
    type: string
    default: "0.0.0"
  - name: azurelinuxVersion
    type: string
    default: "3.0-stable"

variables:
  - template: common-variables.yml@self

resources:
  repositories:
    - repository: ob-templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
    - repository: ContainerPlatform
      type: git
      name: ContainerPlatform/ContainerPlatform
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@ob-templates
  parameters:
    containers:
      # cannot override part of the default value, so replace containers block whole-sale
      # see: https://onebranch.visualstudio.com/OneBranch.Pipelines/_git/GovernedTemplates?path=/v2/Core.Template.yml
      - container: windows_build_container
        image: $(WindowsContainerImage)
        type: Windows
      - container: windows_build_container2
        image: $(WindowsContainerImage2)
        type: Windows
      - container: linux_build_container
        image: $(LinuxContainerImage)
        type: Linux
        endpoint: cplatadoimages ACR
      - container: linux_build_container2
        image: $(LinuxContainerImage2)
        type: Linux
        endpoint: cplatadoimages ACR

    # Need to use OneBranch's checkout so that repo config files are available for CodeQL and other tools.
    # However, having two checkout "groups" means the ADO multi-repo logic does not apply, so manually
    # update the checkout path (which must be relative to $(Pipeline.Workspace)).
    # Can't checkout directly to sources directory because subsequent ContainerPlatform checkout will be inside it.
    #
    # !NOTE: If only one repo is checked out (e.g., the signing stage), then `$(Build.SourcesDirectory)` is
    # that repo's full path, not `$(Pipeline.Workspace)/s`
    git:
      path: "s/Microsoft.hcsshim"

    globalSdl: # https://aka.ms/obpipelines/sdl
      codeql: # https://aka.ms/codeql3000-faq
        # !Note: can't use a codeql3000.yml file since it must be at the repo root, which is not true for the build stage
        compiled:
          enabled: true
        buildIdentifier: hcsshim
        cadence: 72
        language: go,powershell
        sourceRoot: "$(Pipeline.Workspace)/s/Microsoft.hcsshim"
        tsaEnabled: true
        tsaOptionsPath: "$(Pipeline.Workspace)/s/Microsoft.hcsshim/.config/tsaoptions.json"

      # https://eng.ms/docs/products/onebranch/securitycompliancegovernanceandpolicies/sdlforcontainerizedworkflows/credscan
      credscan:
        suppressionsFile: $(Pipeline.Workspace)/s/Microsoft.hcsshim/.config/CredScanSuppressions.json

      # https://eng.ms/docs/products/onebranch/securitycompliancegovernanceandpolicies/sdlforcontainerizedworkflows/customizesdlforcontainerbuilds
      policheck:
        exclusionsFile: $(Pipeline.Workspace)/s/Microsoft.hcsshim/.config/PolicheckExclusion.xml

      suppression:
        suppressionFile: $(Pipeline.Workspace)/s/Microsoft.hcsshim/.config/.gdnsuppress
        suppressionSet: default

      sourcesAnalysisStage:
        enabled: true

      sbom:
        enabled: true

      tsa: # TSA is always enabled during source analysis stage for official builds
        configFile: $(Pipeline.Workspace)/s/Microsoft.hcsshim/.config/tsaoptions.json

    featureFlags:
      EnableCDPxPAT: false
      mariner:
        extraMounts: true
        extraToolchainMounts: true
        chroot: /temp/DockerStage/docker-chroot-
        chrootSuffixes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

    stages:
      - template: shared-build-stages.yml@self
        parameters:
          rpmVersion: ${{ parameters.rpmVersion }}
          azurelinuxVersion: ${{ parameters.azurelinuxVersion }}
